package org.rsb.tyr.models;

import lombok.Data;
import org.rsb.tyr.enums.AllegationType;
import org.springframework.data.neo4j.core.schema.GeneratedValue;
import org.springframework.data.neo4j.core.schema.Id;
import org.springframework.data.neo4j.core.schema.Node;

import java.util.HashSet;
import java.util.Set;

/** Represents an allegation in the database. */
@Data
@Node
public class Allegation {
  /** Default id generated by neo4j. */
  @Id @GeneratedValue private Long id;

  /** Name of the allegation. */
  private String name;

  Allegation(String name) {
    this.name = name;
  }

  public static Set<Allegation> from(Set<AllegationType> allegationTypes) {
    var all = new HashSet<Allegation>();
    allegationTypes.forEach(allegationType -> all.add(new Allegation(allegationType.name())));
    return all;
  }


}
