package org.rsb.tyr.models;

import lombok.Data;
import org.springframework.data.neo4j.core.schema.GeneratedValue;
import org.springframework.data.neo4j.core.schema.Id;
import org.springframework.data.neo4j.core.schema.Node;

/** Represents a country in the database. */
@Data
@Node
public class Country {
  /** Default id generated by neo4j. */
  @Id @GeneratedValue private Long id;

  /** Name of the country. */
  private String name;

  Country(String name) {
    this.name = name;
  }
}
