package org.rsb.tyr.models;

import lombok.Data;
import org.springframework.data.neo4j.core.schema.GeneratedValue;
import org.springframework.data.neo4j.core.schema.Id;
import org.springframework.data.neo4j.core.schema.Node;

/** Represents a crime in the database. */
@Data
@Node
public class Crime {
  /** Default id generated by neo4j. */
  @Id @GeneratedValue private Long id;

  /** Name of the crime. */
  private String name;

  public Crime(String name) {
    this.name = name;
  }
}
