package org.rsb.tyr.models;

import org.springframework.data.neo4j.core.schema.GeneratedValue;
import org.springframework.data.neo4j.core.schema.Id;
import org.springframework.data.neo4j.core.schema.Node;

/** Represents a person in the database. */
@Node
public class Person {
  /** Default id generated by neo4j. */
  @Id @GeneratedValue private long id;
}
