package org.rsb.tyr.models;

import org.springframework.data.neo4j.core.schema.GeneratedValue;
import org.springframework.data.neo4j.core.schema.Id;
import org.springframework.data.neo4j.core.schema.Node;

import java.util.Set;

/** Represents a person in the database. */
@Node
public class Person {
  /** Default id generated by neo4j. */
  @Id @GeneratedValue private long id;

  /** Crime commited by the person */
  private Crime crime;

  /** Country of origin */
  private Country country;

  /** Allegation(s) against the person */
  private Set<Allegation> allegations;

  /**
   * Returns the id of the person.
   *
   * @return id of the person
   */
  public long getId() {
    return id;
  }

  /**
   * Returns the crime committed by the person.
   *
   * @return crime committed by the person
   */
  public Crime getCrime() {
    return crime;
  }

  /**
   * Returns the country of origin of the person.
   *
   * @return country of origin of the person
   */
  public Country getCountry() {
    return country;
  }

  /**
   * Returns the name of the person.
   *
   * @return name of the person
   */
  public Set<Allegation> getAllegations() {
    return allegations;
  }
}
